### PR TITLE
Fix Null Pointers || Automatic turn BungeeCord mode on || JDK Path optional

### LINKED ISSUE #81: Java Version Optional
**What do you have an idea for?**
Base

**Describe your idea**
add a configuration parameter to serverGroups.json to set up the Java location for this server. This is to allow e.g. Spigot 1.8 server to run on java 1.8 and paper 1.17 server to run on java 11. This is preventive for the upcoming change of Paper

### PR DESCRIPTION
**Pull request by TheMagBum**

### CODE REVIEW

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java [hunk 1]
```diff
@@ -234,6 +234,19 @@ private void startServer(BaseServerObject server) {
...
             setProperty(serverProperties, "online-mode", "false");
             setProperty(serverProperties, "server-name", server.getName());
+            File configFile = new File(temporaryDirectory, "spigot.yml");
+            configFile.createNewFile();
+            Yaml yaml = new Yaml();
+            Map<String, Object> config = (Map<String, Object>) yaml.load(new FileReader(configFile));
+            if (config == null) config = new LinkedHashMap<>();
+            Map<String, Object> settings = (Map<String, Object>) config.get("settings");
+            if (settings == null) settings = new LinkedHashMap<>();
+            settings.put("bungeecord", true);
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: We can't force users without any warning to use the bungee mode since this changes the UUID format and can break e.g. permission systems without the users noticing why. 

I think it's best to *read* the value from the spigot.yml and print a warning message if it's false. The user can then change it himself. If we change it ourselves, there must be an option to prevent that.

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/listeners/ServerKick.java [hunk 2]
```diff
@@ -17,6 +18,9 @@ public void onServerKickEvent(ServerKickEvent event) {
             TimoCloudBungee.getInstance().info("No fallback server found");
             return;
         }
+        TimoCloudBungee.getInstance().info(event.getCancelServer().getName() + " kicked player " + event.getPlayer().getName() + " because of: " + TextComponent.toLegacyText(event.getKickReasonComponent()));
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/listeners/ServerKick.java]: Do server owners always want to have a log of the kicked players in their console?

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/commands/utils/CommandFormatUtil.java [hunk 3]
```diff
@@ -73,6 +74,7 @@ public static String formatBoolean(boolean b) {
     }
 
     public static String formatIp(InetAddress ip) {
+        if(Objects.isNull(ip)) return "null";
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/commands/utils/CommandFormatUtil.java]: Please use "ip == null" for better readability.

File: TimoCloud-API/src/main/java/cloud/timo/TimoCloud/api/objects/ProxyGroupObject.java [hunk 4]
```diff
@@ -175,7 +189,13 @@
...
      * Changes the java start parameters
+     *
      * @return A future being completed when the parameters was changed
      */
     APIRequestFuture<Void> setJavaParameters(Collection<String> value);
+
+    /**
+     * @return A String of The JDKPath using to Start the Proxy
+     */
+    String getJdkPath();
```
Comment (TimoZikeli) [inline TimoCloud-API/src/main/java/cloud/timo/TimoCloud/api/objects/ProxyGroupObject.java]: Please replace "jdk" with "jre" here and anywhere else since you don't need the Java Development Kit to run Java applications, but only the Java Runtime Environment (which is included in the JDK though). 
Otherwise, users might get the impression of needing JDK to run TimoCloud. (https://stackoverflow.com/a/1906455/6494319)

**Review by TimoZikeli — CHANGES_REQUESTED** [review]

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/ProxyGroupObjectBasicImplementation.java [hunk 5]
```diff
@@ -52,10 +52,10 @@
     private Collection<String> hostNames;
     @JsonProperty("jp")
     private List<String> javaParameters;
-    @JsonProperty("jdkp")
-    private String jdkPath;
+    @JsonProperty("jdrp")
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/ProxyGroupObjectBasicImplementation.java:55]: This seems to be a typo („jp“ would be sufficient, too)

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java [hunk 6]
```diff
@@ -241,12 +241,11 @@ private void startServer(BaseServerObject server) {
...
-            settings.put("bungeecord", true);
-            FileWriter writer = new FileWriter(configFile);
-            config.put("settings", settings);
-            DumperOptions dumperOptions = new DumperOptions();
-            dumperOptions.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
-            new Yaml(dumperOptions).dump(config, writer);
+            final Boolean bungeeCordMode = (Boolean) settings.getOrDefault("bungeecord", false);
+
+            if (!bungeeCordMode) {
+                TimoCloudBase.getInstance().warning(server.getName() + " is not in BungeeCord mode");
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: Briefly describe the consequences and how to fix it

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java [hunk 7]
```diff
@@ -101,7 +101,7 @@ public void start() {
                     .set("maxplayersperproxy", getGroup().getMaxPlayerCountPerProxy())
                     .set("globalHash", HashUtil.getHashes(TimoCloudCore.getInstance().getFileManager().getProxyGlobalDirectory()))
                     .set("javaParameters", getGroup().getJavaParameters())
-                    .set("jdkPath", getGroup().getJdkPath());
+                    .set("jdkPath", getGroup().getJrePath());
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java]: jrePath

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java [hunk 8]
```diff
@@ -83,7 +83,7 @@ public void start() {
                     .set("globalHash", HashUtil.getHashes(TimoCloudCore.getInstance().getFileManager().getServerGlobalDirectory()))
                     .set("spigotParameters", getGroup().getSpigotParameters())
                     .set("javaParameters", getGroup().getJavaParameters())
-                    .set("jdkPath", getGroup().getJdkPath());
+                    .set("jdkPath", getGroup().getJrePath());
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java]: jrePath

Comment (TimoZikeli) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java]: Also change it on the other end

**Review by TimoZikeli — CHANGES_REQUESTED** [review]
Please change the commented sections, then test if server- and proxy starting still works.
Thanks!

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/ProxyGroupObjectBasicImplementation.java (hunk 5 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/ProxyGroupObjectBasicImplementation.java:55]: jp already used?

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java (hunk 7 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java]: what you mean?

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java (hunk 8 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java]: what you mean?

**Review by TimoZikeli — APPROVED** [review]
