### PR TITLE
add sendMessage to PlayerObject || Add StringBuilder instanceof String in SocketClientHandlers || InaccessibleObjectException Gson Fix || Add Velocity support for 3.x || Add timeoutsystem

### LINKED ISSUE #54: Screen wird gekillt, nach bestimmter Zeit wo keine Reaktion kam
**What do you have an idea for?**
Server / Proxy

**Describe your idea**
Wenn der Server aus den server.properties die max-tick-time Sekunden kein bestimmtes Signal sendet, wird die Screen-Session gekillt

**Additional context**
-

### LINKED ISSUE #88: jrePath in editServerGroup
**What do you have an idea for?**
Core

**Describe your idea**
add a parameter to editServerGroup so that you can change the jrePath.

### LINKED ISSUE #89: Use a StringBuilder in SocketClientHandlers
Currently, all TimoCloud modules use kind of the same `SocketClientHandler`, like https://github.com/TimoCloud/TimoCloud/blob/master/TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/bungeecord/sockets/BungeeSocketClientHandler.java

When sending messages before the socket connection is established, a message queue is used – represented as a simple string. Each time a new message is appended to the queue, Java duplicates the string. Use a `StringBuilder` instead.

Create a BasicSocketClientHandler implementing the common functionality and let all SocketClientHandlers extend it.

### LINKED ISSUE #99: SendMessage for PlayerObject
**What do you have an idea for?**
General

**Describe your idea**
SendMessage Method for PlayerObject to send a Message over the Cloud

### LINKED ISSUE #101: InaccessibleObjectException on Server start
**Describe the bug**
When a Server uses the Map System of TimoCloud an InaccessibleObjectException apears at Server start and it wont register

**To Reproduce**
1. Where does it happen? Server
2. When does it happen? Start
3. Do you know why it happens? Gson Error

**Expected behavior**
Server starts without error

**Stacktrace**
[20:07:05 INFO]: [TimoCloud] Uncaught exception while calling method onPluginMessage:
[20:07:05 WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @2baf3d81
[20:07:05 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[20:07:05 WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[20:07:05 WARN]:        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[20:07:05 WARN]:        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[20:07:05 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:157)
[20:07:05 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[20:07:05 WARN]:        at com.google.gson.Gson.getAdapter(Gson.java:423)
[20:07:05 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
[20:07:05 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
[20:07:05 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
[20:07:05 WARN]:        at com.google.gson.Gson.getAdapter(Gson.java:423)
[20:07:05 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:886)
[20:07:05 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:952)
[20:07:05 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:925)
[20:07:05 WARN]:        at cloud.timo.TimoCloud.common.json.JsonConverter.convertMapIfNecessary(JsonConverter.java:12)
[20:07:05 WARN]:        at cloud.timo.TimoCloud.api.implementations.async.APIResponse.fromPluginMessage(APIResponse.java:53)
[20:07:05 WARN]:        at cloud.timo.TimoCloud.api.implementations.managers.APIResponseManager.onPluginMessage(APIResponseManager.java:19)
[20:07:05 WARN]:        at cloud.timo.TimoCloud.api.implementations.TimoCloudMessageAPIBasicImplementation.onMessage(TimoCloudMessageAPIBasicImplementation.java:76)
[20:07:05 WARN]:        at cloud.timo.TimoCloud.bukkit.sockets.BukkitStringHandler.handleMessage(BukkitStringHandler.java:53)
[20:07:05 WARN]:        at cloud.timo.TimoCloud.common.sockets.BasicStringHandler.channelRead0(BasicStringHandler.java:15)
[20:07:05 WARN]:        at cloud.timo.TimoCloud.common.sockets.BasicStringHandler.channelRead0(BasicStringHandler.java:9)
[20:07:05 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:07:05 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:07:05 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[20:07:05 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:07:05 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[20:07:05 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:07:05 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:07:05 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:07:05 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:07:05 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[20:07:05 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[20:07:05 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[20:07:05 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:07:05 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:07:05 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[20:07:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Operating System (please complete the following information):**
 - OS: Debian
 - Version 11

### PR DESCRIPTION
**Pull request by TheMagBum**

### CODE REVIEW

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/properties/ProxyGroupDefaultPropertiesProviderImplementation.java [hunk 1]
```diff
@@ -90,4 +90,10 @@ public String getJrePath() {
     public String generateId() {
         return RandomIdGenerator.generateId();
     }
+
+    @Override
+    public int getTimeout() {
+        return 180000;
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/properties/ProxyGroupDefaultPropertiesProviderImplementation.java]: Please make this more human-readable like `1000*60*3`

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/properties/ServerGroupDefaultPropertiesProviderImplementation.java [hunk 2]
```diff
@@ -73,4 +73,9 @@ public String generateId() {
     public String getJrePath() {
         return "java";
     }
+
+    @Override
+    public int getTimeout() {
+        return 180000;
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/api/implementations/objects/properties/ServerGroupDefaultPropertiesProviderImplementation.java]: Same here

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java [hunk 3]
```diff
@@ -305,19 +309,63 @@ private void startServer(BaseServerObject server) {
...
 
-            TimoCloudBase.getInstance().getSocketMessageManager().sendMessage(Message.create()
-                    .setType(MessageType.BASE_SERVER_STARTED)
-                    .setTarget(server.getId())
-                    .set("port", serverPort)
-                    .set("publicKey", RSAKeyUtil.publicKeyToBase64(publicKey))
-            );
-
+            //delay because we can only get the pid after 20 Millis.
+            new java.util.Timer().schedule(
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java:313]: Please use the lambda syntax: `schedule(() -> {...})`

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java [hunk 4]
```diff
@@ -305,19 +309,63 @@ private void startServer(BaseServerObject server) {
...
+                                        .set("port", serverPort)
+                                        .set("publicKey", RSAKeyUtil.publicKeyToBase64(publicKey))
+                                        .set("pid", pid)
+                                );
+                            } catch (Exception e) {
+                                TimoCloudBase.getInstance().severe("Error while starting server " + server.getName() + ": " + e.getMessage());
+                                TimoCloudBase.getInstance().getSocketMessageManager().sendMessage(Message.create().setType(MessageType.BASE_SERVER_NOT_STARTED).setTarget(server.getId()));
+                            }
+                        }
+                    }, 20);
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: I wouldn't hardcode a limit because this could depend on the system load. Rather, I would do it in a loop (with a maximum amount of retries), always waiting 20ms between the tries.

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java [hunk 5]
```diff
@@ -512,12 +560,28 @@ private void startProxy(BaseProxyObject proxy) {
...
-            TimoCloudBase.getInstance().getSocketMessageManager().sendMessage(Message.create()
-                    .setType(MessageType.BASE_PROXY_STARTED)
-                    .setTarget(proxy.getId())
-                    .set("port", proxyPort)
-                    .set("publicKey", RSAKeyUtil.publicKeyToBase64(publicKey))
-            );
+
+            //delay because we can only get the pid after 20 Millis.
+            final int finalProxyPort = proxyPort;
+            new Timer().schedule(
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: (Same changes here)

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/common/protocol/MessageType.java [hunk 6]
```diff
@@ -50,6 +51,9 @@
     BASE_SERVER_NOT_STARTED                     (36),
     BASE_PROXY_STARTED                          (37),
     BASE_PROXY_NOT_STARTED                      (38),
+    BASE_INSTANCE_KILL                          (53),
+    BASE_PID_EXIST_REQUEST                      (54),
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/common/protocol/MessageType.java]: Please briefly explain what this does in a comment

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java [hunk 7]
```diff
@@ -46,6 +52,9 @@
     private Set<Server> registeredServers;
     private LogStorage logStorage;
     private PublicKey publicKey;
+    private int pid;
+    private final ScheduledExecutorService scheduler;
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java:56]: Also shutdown the scheduler when the proxy is shut down

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java [hunk 8]
```diff
@@ -59,8 +68,22 @@ public Proxy(String name, String id, Base base, ProxyGroup group) {
...
+        scheduler = Executors.newScheduledThreadPool(1);
+        scheduler.scheduleAtFixedRate(this::requestPidStatus, 5, 5, TimeUnit.SECONDS);
+        scheduler.scheduleAtFixedRate(this::checkTimeout, 5, 5, TimeUnit.SECONDS);
+    }
+
+    private void checkTimeout() {
+        if (System.currentTimeMillis() - lastContact > getGroup().getTimeout()) {
+            //Timeout
+            kill();
+            TimoCloudCore.getInstance().info("Proxy " + getName() + " timed out.");
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java]: `.warning(`

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java [hunk 9]
```diff
@@ -62,6 +68,19 @@ public Server(String name, String id, Base base, String map, ServerGroup group)
...
+        scheduler = Executors.newScheduledThreadPool(1);
+        scheduler.scheduleAtFixedRate(this::requestPidStatus, 5, 5, TimeUnit.SECONDS);
+        scheduler.scheduleAtFixedRate(this::checkTimeout, 5, 5, TimeUnit.SECONDS);
+    }
+
+    private void checkTimeout() {
+        if (System.currentTimeMillis() - lastContact > getGroup().getTimeout()) {
+            //Timeout
+            kill();
+            TimoCloudCore.getInstance().info("Server " + getName() + " timed out.");
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java]: (Same here)

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java [hunk 10]
```diff
@@ -49,6 +52,9 @@
     private boolean connected;
     private LogStorage logStorage;
     private PublicKey publicKey;
+    private int pid;
+    private final ScheduledExecutorService scheduler;
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java:56]: (Same here)

**Review by TimoZikeli — CHANGES_REQUESTED** [review]
Thank you for the changes!
Please consider the suggestions.

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java (hunk 3 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java:313]: This is not supported by java 8 as far as I know

Comment (TimoZikeli) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java:313]: Ok it generally works of course, but not with TimerTask: https://stackoverflow.com/a/37970821/6494319

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java (hunk 7 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Proxy.java:56]: isn't this already in line 109?
onShutdown

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java (hunk 10 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/core/objects/Server.java:56]: isn't this already in line 218?
onShutdown

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java (hunk 3 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java:313]: Should I replace the TaskTimer then?

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java [hunk 11]
```diff
@@ -309,7 +309,8 @@ private void startServer(BaseServerObject server) {
                 throw new ServerStartException("Could not start process");
             }
 
-            //delay because we can only get the pid after 20 Millis.
+            final int[] retriesLeft = new int[]{10};
```
Comment (TimoZikeli) [inline TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: Why are you using an array? Where is it initialized?

**Review by TimoZikeli — CHANGES_REQUESTED** [review]

File: TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java (hunk 11 above)
Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: what should i use instead?

Comment (TimoZikeli) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: An integer variable?

Comment (TheMagBum) [reply TimoCloud-Universal/src/main/java/cloud/timo/TimoCloud/base/managers/BaseInstanceManager.java]: because atomicintegers are disgusting

**Review by TimoZikeli — APPROVED** [review]
